### ISSUE TITLE
M5Stack.power_off() does not work

### ISSUE THREAD

**Issue by jake-walker** [lemariva/micropython-core2#2]
The `power_off()` function in the M5Stack class is calling a function that is not defined in [`machine.axp192`](https://github.com/lemariva/micropython-core2/blob/master/source/ports/esp32/machine_axp192.c) so an error is raised when using the power off function.

https://github.com/lemariva/micropython-core2/blob/master/source/ports/esp32/boards/M5CORE2_BOARD/modules/m5stack.py#L66

**Comment by lemariva** [comment]
You're right. The function was `shutdown()`. I changed that in the latest release. Check that out.
