### ISSUE TITLE
When will this be fixed to reflect the real UIFlow libs on the device

### ISSUE THREAD

**Issue by hjgode** [lemariva/micropython-core2#5]
Hello

most of the libs are not on the device or behave different. The examples (ie mqtt) cannot be used as UIFlow 1.8.1 implements everything a bit different.

Really need a true MicroPython UIFlow Core2 reference documentation that is correct.

**Comment by lemariva** [comment]
In the latest firmware, I removed the `umqtt` freeze module. I recommend you install the version that you want. You can do that by connecting the m2core to the Internet and using the following commands over REPL:
```
import upip
upip.install('micropython-umqtt.simple')
```
This will install the `umqtt.simple` library from https://pypi.org/project/micropython-umqtt.simple/ and you can check the help over there.
